require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"

AllCops:
  Exclude:
    - public/**/*
    - tmp/**/*
    - log/**/*
    - bin/**/*
    - config/**/*
    - config/**/*
    - config.ru
    - db/migrate/*
    - db/schema.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*

